spring.application.name=netproxi
spring.datasource.url=jdbc:postgresql://localhost:543/cleaningdb
spring.datasource.username=cleaninguser
spring.datasource.password=cleaningpass

# HikariCP Connection Pool Configuration
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.idleTimeout=300000
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maxLifetime=1200000

# JTA Platform Configuration
spring.jpa.properties.jta.platform=org.hibernate.service.jta.platform.internal.JtaPlatformImpl

jwt.secret=ySddkR/wHCbhMHMgKh/Qz41CIKCXCaIudl/ckJt000cfS/uaZDStqmSVsCyFoRKPY7WZ7RK3ir8srhVu4LUwMg==
jwt.expirationMs=3600000
jwt.refreshExpirationMs=604800000

springdoc.swagger-ui.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

